prompt_suffixes = {"photo": " Photography, DSLR, 35mm lens, f 1.4, sharp, natural light, bokeh.",
                   "painting": " Painting, chiaroscuro, baroque, renaissance, masterpiece.",
                   "digital art": " Digital art, concept art, cinematic lighting, trending on artstation, trending on cgsociety.",
                   "3d render": " 3D render, unreal engine, zbrush.",
                   "realism": " Hyper-realistic, elegant, realistic color.",
                   "detailed": " High detail, intricate, good contrast.",
                   "hd": " Sharp, hd, 4k, 8k."}

artists = ['Edmund Leighton',
           'John William Waterhouse',
           'Joseph Wright of Derby',
           'William Turner',
           'Joseph Vernet',
           'Rembrandt',
           'Ernst Haeckel',
           'Alphonse Mucha',
           'Greg Rutkowski',
           'John Bauer',
           'Tove Jansson',
           'Jöns-Bertil Falukorv']